### ISSUE TITLE
Invoice Canister Cleanup Tasks

### ISSUE THREAD

**Issue by krpeacock** [dfinity/examples#292]
- [x] Ensure that person without viewing permission cannot view an already verified invoice
  - invoice.mo line 283
- [x] Gitignore src/declarations
- [x] replace dfx stop with `#!/usr/bin/env bash;  set -e; dfx stop
- [ ] Add access control for creating new invoices
- [x] Check account for transfer fee during transfer
  - ICPLedger.mo line 179
- [x] pull magic numbers into constants
  - main.mo line 139
- [ ] Refactor permission checks to a method

**Comment by AshtonEngberg** [comment]
Is it possible to uncheck " Check account for transfer fee during transfer " ? 

The current logic doesn't actually fix this problem--the way to resolve it is require a minimum payable amount for creating invoices (if the token is ICP or ICRC-1). Since an invoice requires at least one transfer by the invoice canister that the payable amount must cover (from invoice subaccount to principal subaccount), I'd suggest the minimum to be twice the transfer fee. 

Somewhat similar to this issue, https://github.com/dfinity/invoice-canister/issues/35, I'd like to fix both in future commits as part of the bounty since otherwise this current pull request is ready to go (uploading it soon).

**Comment by AshtonEngberg** [comment]
More of a general question, but couldn't all the specific result return types anonymously declared in the function itself be moved into its own module (or extended as a part of the Types)? This would make the invoice canister's code much more concise, which presumably would make it easier to grok or iterate development unless there's a reason it should be styled the way it is?
