### ISSUE TITLE
Azle (TypeScript) examples

### ISSUE THREAD

**Issue by lastmjs** [dfinity/examples#318]
[Azle](https://github.com/demergent-labs/azle) is a TypeScript CDK for the Internet Computer. We've been creating many examples, some from this repo, [here](https://github.com/demergent-labs/azle/tree/main/examples). Just wondering if you'd accept pull requests for examples written in TypeScript with Azle.

**Comment by sesi200** [comment]
Hi Jordan, apologies for the ridiculously late response. If I don't respond within 2-3 days it means that I missed the request. Feel free to ping me again next time. 

After some back and forth we decided that for now, we do not accept examples in more frameworks to the repo because of the maintenance burden of keeping up with many different frameworks. Our consensus was basically "If it was only Jordan, we'd accept in a heartbeat, but we don't want to set the precedent."

I can present you two alternatives that you hopefully like (and would be happy about feedback):
- Adding an overview of Azle and plenty of links to your examples to our documentation as described in [this forum post](https://forum.dfinity.org/t/incorporating-more-community-tooling-sdks-repos-into-ic-docs/14960)
- We have a community section planned for the [official sample code page](https://internetcomputer.org/samples). There, we'd love to have links to as many of your individual examples as you like adding. We'll have some simple instructions on how to add them, too. Last I heard it was planned for roughly next week, but you know how good we are at keeping schedules...

**Comment by lastmjs** [comment]
This all sounds great, thanks!

**Comment by sesi200** [comment]
Adding an example:
- Add your project to `/static/supernovaProjects.json` (Yes, I know the name is inaccurate, but it works)
- Add the picture for your tile to `/static/img/samples/supernovaSubmissions`

I agree that the language filter is not perfect as is, but I can't get anyone to rework that right now. You could, however, add Azle or TypeScript as a Language in `/src/components/SamplesPage/FilterBar/index.tsx`
